development: 
  options: 
    raise_not_found_error: false
  sessions: 
    default: 
      database: omertex_development
      hosts: 
        - "localhost:27017"
      options: ~
production: 
  sessions: 
    default: 
      options:
      uri: <%= ENV['MONGOLAB_URI'] %>
  options:
    raise_not_found_error: false
test: 
  sessions: 
    default: 
      database: omertex_test
      hosts: 
        - "localhost:27017"
      options: 
        max_retries: 1
        read: primary
        retry_interval: 0
        skip_version_check: true
